// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadatos.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataAvion struct {
	Aerolinea            string   `protobuf:"bytes,1,opt,name=aerolinea,proto3" json:"aerolinea,omitempty"`
	Codigo               string   `protobuf:"bytes,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	PesoMax              int32    `protobuf:"varint,3,opt,name=pesoMax,proto3" json:"pesoMax,omitempty"`
	CapTanque            int32    `protobuf:"varint,4,opt,name=CapTanque,proto3" json:"CapTanque,omitempty"`
	IpTorreInicial       string   `protobuf:"bytes,5,opt,name=ipTorreInicial,proto3" json:"ipTorreInicial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAvion) Reset()         { *m = DataAvion{} }
func (m *DataAvion) String() string { return proto.CompactTextString(m) }
func (*DataAvion) ProtoMessage()    {}
func (*DataAvion) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{0}
}

func (m *DataAvion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAvion.Unmarshal(m, b)
}
func (m *DataAvion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAvion.Marshal(b, m, deterministic)
}
func (m *DataAvion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAvion.Merge(m, src)
}
func (m *DataAvion) XXX_Size() int {
	return xxx_messageInfo_DataAvion.Size(m)
}
func (m *DataAvion) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAvion.DiscardUnknown(m)
}

var xxx_messageInfo_DataAvion proto.InternalMessageInfo

func (m *DataAvion) GetAerolinea() string {
	if m != nil {
		return m.Aerolinea
	}
	return ""
}

func (m *DataAvion) GetCodigo() string {
	if m != nil {
		return m.Codigo
	}
	return ""
}

func (m *DataAvion) GetPesoMax() int32 {
	if m != nil {
		return m.PesoMax
	}
	return 0
}

func (m *DataAvion) GetCapTanque() int32 {
	if m != nil {
		return m.CapTanque
	}
	return 0
}

func (m *DataAvion) GetIpTorreInicial() string {
	if m != nil {
		return m.IpTorreInicial
	}
	return ""
}

type ResponseTorre struct {
	Estado               bool     `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje              string   `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseTorre) Reset()         { *m = ResponseTorre{} }
func (m *ResponseTorre) String() string { return proto.CompactTextString(m) }
func (*ResponseTorre) ProtoMessage()    {}
func (*ResponseTorre) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{1}
}

func (m *ResponseTorre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseTorre.Unmarshal(m, b)
}
func (m *ResponseTorre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseTorre.Marshal(b, m, deterministic)
}
func (m *ResponseTorre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseTorre.Merge(m, src)
}
func (m *ResponseTorre) XXX_Size() int {
	return xxx_messageInfo_ResponseTorre.Size(m)
}
func (m *ResponseTorre) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseTorre.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseTorre proto.InternalMessageInfo

func (m *ResponseTorre) GetEstado() bool {
	if m != nil {
		return m.Estado
	}
	return false
}

func (m *ResponseTorre) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

type DataDespegue struct {
	Destino              string   `protobuf:"bytes,1,opt,name=destino,proto3" json:"destino,omitempty"`
	Aerolinea            string   `protobuf:"bytes,2,opt,name=aerolinea,proto3" json:"aerolinea,omitempty"`
	Codigo               string   `protobuf:"bytes,3,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Pista                int32    `protobuf:"varint,4,opt,name=pista,proto3" json:"pista,omitempty"`
	SegundaInstancia     bool     `protobuf:"varint,5,opt,name=segundaInstancia,proto3" json:"segundaInstancia,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDespegue) Reset()         { *m = DataDespegue{} }
func (m *DataDespegue) String() string { return proto.CompactTextString(m) }
func (*DataDespegue) ProtoMessage()    {}
func (*DataDespegue) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{2}
}

func (m *DataDespegue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDespegue.Unmarshal(m, b)
}
func (m *DataDespegue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDespegue.Marshal(b, m, deterministic)
}
func (m *DataDespegue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDespegue.Merge(m, src)
}
func (m *DataDespegue) XXX_Size() int {
	return xxx_messageInfo_DataDespegue.Size(m)
}
func (m *DataDespegue) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDespegue.DiscardUnknown(m)
}

var xxx_messageInfo_DataDespegue proto.InternalMessageInfo

func (m *DataDespegue) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *DataDespegue) GetAerolinea() string {
	if m != nil {
		return m.Aerolinea
	}
	return ""
}

func (m *DataDespegue) GetCodigo() string {
	if m != nil {
		return m.Codigo
	}
	return ""
}

func (m *DataDespegue) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *DataDespegue) GetSegundaInstancia() bool {
	if m != nil {
		return m.SegundaInstancia
	}
	return false
}

type ResponseDespegue struct {
	Estado               bool     `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Ipdestino            string   `protobuf:"bytes,2,opt,name=ipdestino,proto3" json:"ipdestino,omitempty"`
	Mensaje              string   `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Pista                int32    `protobuf:"varint,4,opt,name=pista,proto3" json:"pista,omitempty"`
	Altura               int32    `protobuf:"varint,5,opt,name=altura,proto3" json:"altura,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseDespegue) Reset()         { *m = ResponseDespegue{} }
func (m *ResponseDespegue) String() string { return proto.CompactTextString(m) }
func (*ResponseDespegue) ProtoMessage()    {}
func (*ResponseDespegue) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{3}
}

func (m *ResponseDespegue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDespegue.Unmarshal(m, b)
}
func (m *ResponseDespegue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDespegue.Marshal(b, m, deterministic)
}
func (m *ResponseDespegue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDespegue.Merge(m, src)
}
func (m *ResponseDespegue) XXX_Size() int {
	return xxx_messageInfo_ResponseDespegue.Size(m)
}
func (m *ResponseDespegue) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDespegue.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDespegue proto.InternalMessageInfo

func (m *ResponseDespegue) GetEstado() bool {
	if m != nil {
		return m.Estado
	}
	return false
}

func (m *ResponseDespegue) GetIpdestino() string {
	if m != nil {
		return m.Ipdestino
	}
	return ""
}

func (m *ResponseDespegue) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

func (m *ResponseDespegue) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *ResponseDespegue) GetAltura() int32 {
	if m != nil {
		return m.Altura
	}
	return 0
}

type DataAterrizaje struct {
	Aerolinea            string   `protobuf:"bytes,1,opt,name=aerolinea,proto3" json:"aerolinea,omitempty"`
	Codigo               string   `protobuf:"bytes,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	PesoMax              int32    `protobuf:"varint,3,opt,name=pesoMax,proto3" json:"pesoMax,omitempty"`
	CapTanque            int32    `protobuf:"varint,4,opt,name=CapTanque,proto3" json:"CapTanque,omitempty"`
	IpTorreActual        string   `protobuf:"bytes,5,opt,name=ipTorreActual,proto3" json:"ipTorreActual,omitempty"`
	Pista                int32    `protobuf:"varint,6,opt,name=pista,proto3" json:"pista,omitempty"`
	SegundaInstancia     bool     `protobuf:"varint,7,opt,name=segundaInstancia,proto3" json:"segundaInstancia,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAterrizaje) Reset()         { *m = DataAterrizaje{} }
func (m *DataAterrizaje) String() string { return proto.CompactTextString(m) }
func (*DataAterrizaje) ProtoMessage()    {}
func (*DataAterrizaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{4}
}

func (m *DataAterrizaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAterrizaje.Unmarshal(m, b)
}
func (m *DataAterrizaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAterrizaje.Marshal(b, m, deterministic)
}
func (m *DataAterrizaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAterrizaje.Merge(m, src)
}
func (m *DataAterrizaje) XXX_Size() int {
	return xxx_messageInfo_DataAterrizaje.Size(m)
}
func (m *DataAterrizaje) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAterrizaje.DiscardUnknown(m)
}

var xxx_messageInfo_DataAterrizaje proto.InternalMessageInfo

func (m *DataAterrizaje) GetAerolinea() string {
	if m != nil {
		return m.Aerolinea
	}
	return ""
}

func (m *DataAterrizaje) GetCodigo() string {
	if m != nil {
		return m.Codigo
	}
	return ""
}

func (m *DataAterrizaje) GetPesoMax() int32 {
	if m != nil {
		return m.PesoMax
	}
	return 0
}

func (m *DataAterrizaje) GetCapTanque() int32 {
	if m != nil {
		return m.CapTanque
	}
	return 0
}

func (m *DataAterrizaje) GetIpTorreActual() string {
	if m != nil {
		return m.IpTorreActual
	}
	return ""
}

func (m *DataAterrizaje) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *DataAterrizaje) GetSegundaInstancia() bool {
	if m != nil {
		return m.SegundaInstancia
	}
	return false
}

type ResponseAterrizaje struct {
	Estado               bool     `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje              string   `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Pista                int32    `protobuf:"varint,3,opt,name=pista,proto3" json:"pista,omitempty"`
	Altura               int32    `protobuf:"varint,4,opt,name=altura,proto3" json:"altura,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAterrizaje) Reset()         { *m = ResponseAterrizaje{} }
func (m *ResponseAterrizaje) String() string { return proto.CompactTextString(m) }
func (*ResponseAterrizaje) ProtoMessage()    {}
func (*ResponseAterrizaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{5}
}

func (m *ResponseAterrizaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAterrizaje.Unmarshal(m, b)
}
func (m *ResponseAterrizaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAterrizaje.Marshal(b, m, deterministic)
}
func (m *ResponseAterrizaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAterrizaje.Merge(m, src)
}
func (m *ResponseAterrizaje) XXX_Size() int {
	return xxx_messageInfo_ResponseAterrizaje.Size(m)
}
func (m *ResponseAterrizaje) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAterrizaje.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAterrizaje proto.InternalMessageInfo

func (m *ResponseAterrizaje) GetEstado() bool {
	if m != nil {
		return m.Estado
	}
	return false
}

func (m *ResponseAterrizaje) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

func (m *ResponseAterrizaje) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *ResponseAterrizaje) GetAltura() int32 {
	if m != nil {
		return m.Altura
	}
	return 0
}

type DataDestino struct {
	Destino              string   `protobuf:"bytes,1,opt,name=destino,proto3" json:"destino,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDestino) Reset()         { *m = DataDestino{} }
func (m *DataDestino) String() string { return proto.CompactTextString(m) }
func (*DataDestino) ProtoMessage()    {}
func (*DataDestino) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{6}
}

func (m *DataDestino) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDestino.Unmarshal(m, b)
}
func (m *DataDestino) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDestino.Marshal(b, m, deterministic)
}
func (m *DataDestino) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDestino.Merge(m, src)
}
func (m *DataDestino) XXX_Size() int {
	return xxx_messageInfo_DataDestino.Size(m)
}
func (m *DataDestino) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDestino.DiscardUnknown(m)
}

var xxx_messageInfo_DataDestino proto.InternalMessageInfo

func (m *DataDestino) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

type ResponseDestino struct {
	Estado               bool     `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseDestino) Reset()         { *m = ResponseDestino{} }
func (m *ResponseDestino) String() string { return proto.CompactTextString(m) }
func (*ResponseDestino) ProtoMessage()    {}
func (*ResponseDestino) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{7}
}

func (m *ResponseDestino) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDestino.Unmarshal(m, b)
}
func (m *ResponseDestino) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDestino.Marshal(b, m, deterministic)
}
func (m *ResponseDestino) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDestino.Merge(m, src)
}
func (m *ResponseDestino) XXX_Size() int {
	return xxx_messageInfo_ResponseDestino.Size(m)
}
func (m *ResponseDestino) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDestino.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDestino proto.InternalMessageInfo

func (m *ResponseDestino) GetEstado() bool {
	if m != nil {
		return m.Estado
	}
	return false
}

type AvisoDespegue struct {
	Pista                int32    `protobuf:"varint,1,opt,name=pista,proto3" json:"pista,omitempty"`
	Codigo               string   `protobuf:"bytes,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Lugar                string   `protobuf:"bytes,3,opt,name=lugar,proto3" json:"lugar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvisoDespegue) Reset()         { *m = AvisoDespegue{} }
func (m *AvisoDespegue) String() string { return proto.CompactTextString(m) }
func (*AvisoDespegue) ProtoMessage()    {}
func (*AvisoDespegue) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{8}
}

func (m *AvisoDespegue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvisoDespegue.Unmarshal(m, b)
}
func (m *AvisoDespegue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvisoDespegue.Marshal(b, m, deterministic)
}
func (m *AvisoDespegue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvisoDespegue.Merge(m, src)
}
func (m *AvisoDespegue) XXX_Size() int {
	return xxx_messageInfo_AvisoDespegue.Size(m)
}
func (m *AvisoDespegue) XXX_DiscardUnknown() {
	xxx_messageInfo_AvisoDespegue.DiscardUnknown(m)
}

var xxx_messageInfo_AvisoDespegue proto.InternalMessageInfo

func (m *AvisoDespegue) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *AvisoDespegue) GetCodigo() string {
	if m != nil {
		return m.Codigo
	}
	return ""
}

func (m *AvisoDespegue) GetLugar() string {
	if m != nil {
		return m.Lugar
	}
	return ""
}

type ResponseMensaje struct {
	Mensaje              string   `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMensaje) Reset()         { *m = ResponseMensaje{} }
func (m *ResponseMensaje) String() string { return proto.CompactTextString(m) }
func (*ResponseMensaje) ProtoMessage()    {}
func (*ResponseMensaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{9}
}

func (m *ResponseMensaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMensaje.Unmarshal(m, b)
}
func (m *ResponseMensaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMensaje.Marshal(b, m, deterministic)
}
func (m *ResponseMensaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMensaje.Merge(m, src)
}
func (m *ResponseMensaje) XXX_Size() int {
	return xxx_messageInfo_ResponseMensaje.Size(m)
}
func (m *ResponseMensaje) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMensaje.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMensaje proto.InternalMessageInfo

func (m *ResponseMensaje) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

type Mensajes struct {
	Mensaje              string   `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mensajes) Reset()         { *m = Mensajes{} }
func (m *Mensajes) String() string { return proto.CompactTextString(m) }
func (*Mensajes) ProtoMessage()    {}
func (*Mensajes) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{10}
}

func (m *Mensajes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mensajes.Unmarshal(m, b)
}
func (m *Mensajes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mensajes.Marshal(b, m, deterministic)
}
func (m *Mensajes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mensajes.Merge(m, src)
}
func (m *Mensajes) XXX_Size() int {
	return xxx_messageInfo_Mensajes.Size(m)
}
func (m *Mensajes) XXX_DiscardUnknown() {
	xxx_messageInfo_Mensajes.DiscardUnknown(m)
}

var xxx_messageInfo_Mensajes proto.InternalMessageInfo

func (m *Mensajes) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

type ResponseDepartures struct {
	Departures           []*ObjectDepartures `protobuf:"bytes,1,rep,name=departures,proto3" json:"departures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ResponseDepartures) Reset()         { *m = ResponseDepartures{} }
func (m *ResponseDepartures) String() string { return proto.CompactTextString(m) }
func (*ResponseDepartures) ProtoMessage()    {}
func (*ResponseDepartures) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{11}
}

func (m *ResponseDepartures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDepartures.Unmarshal(m, b)
}
func (m *ResponseDepartures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDepartures.Marshal(b, m, deterministic)
}
func (m *ResponseDepartures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDepartures.Merge(m, src)
}
func (m *ResponseDepartures) XXX_Size() int {
	return xxx_messageInfo_ResponseDepartures.Size(m)
}
func (m *ResponseDepartures) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDepartures.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDepartures proto.InternalMessageInfo

func (m *ResponseDepartures) GetDepartures() []*ObjectDepartures {
	if m != nil {
		return m.Departures
	}
	return nil
}

type ResponseArrivals struct {
	Arrivals             []*ObjectArrivals `protobuf:"bytes,1,rep,name=arrivals,proto3" json:"arrivals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseArrivals) Reset()         { *m = ResponseArrivals{} }
func (m *ResponseArrivals) String() string { return proto.CompactTextString(m) }
func (*ResponseArrivals) ProtoMessage()    {}
func (*ResponseArrivals) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{12}
}

func (m *ResponseArrivals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseArrivals.Unmarshal(m, b)
}
func (m *ResponseArrivals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseArrivals.Marshal(b, m, deterministic)
}
func (m *ResponseArrivals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseArrivals.Merge(m, src)
}
func (m *ResponseArrivals) XXX_Size() int {
	return xxx_messageInfo_ResponseArrivals.Size(m)
}
func (m *ResponseArrivals) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseArrivals.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseArrivals proto.InternalMessageInfo

func (m *ResponseArrivals) GetArrivals() []*ObjectArrivals {
	if m != nil {
		return m.Arrivals
	}
	return nil
}

type ObjectDepartures struct {
	CodigoAvion          string   `protobuf:"bytes,1,opt,name=codigoAvion,proto3" json:"codigoAvion,omitempty"`
	Destino              string   `protobuf:"bytes,2,opt,name=destino,proto3" json:"destino,omitempty"`
	PistaDespegue        string   `protobuf:"bytes,3,opt,name=pistaDespegue,proto3" json:"pistaDespegue,omitempty"`
	HoraDespegue         string   `protobuf:"bytes,4,opt,name=horaDespegue,proto3" json:"horaDespegue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectDepartures) Reset()         { *m = ObjectDepartures{} }
func (m *ObjectDepartures) String() string { return proto.CompactTextString(m) }
func (*ObjectDepartures) ProtoMessage()    {}
func (*ObjectDepartures) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{13}
}

func (m *ObjectDepartures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDepartures.Unmarshal(m, b)
}
func (m *ObjectDepartures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDepartures.Marshal(b, m, deterministic)
}
func (m *ObjectDepartures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDepartures.Merge(m, src)
}
func (m *ObjectDepartures) XXX_Size() int {
	return xxx_messageInfo_ObjectDepartures.Size(m)
}
func (m *ObjectDepartures) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDepartures.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDepartures proto.InternalMessageInfo

func (m *ObjectDepartures) GetCodigoAvion() string {
	if m != nil {
		return m.CodigoAvion
	}
	return ""
}

func (m *ObjectDepartures) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *ObjectDepartures) GetPistaDespegue() string {
	if m != nil {
		return m.PistaDespegue
	}
	return ""
}

func (m *ObjectDepartures) GetHoraDespegue() string {
	if m != nil {
		return m.HoraDespegue
	}
	return ""
}

type ObjectArrivals struct {
	CodigoAvion          string   `protobuf:"bytes,1,opt,name=codigoAvion,proto3" json:"codigoAvion,omitempty"`
	Proveniente          string   `protobuf:"bytes,2,opt,name=proveniente,proto3" json:"proveniente,omitempty"`
	PistaLlegada         string   `protobuf:"bytes,3,opt,name=pistaLlegada,proto3" json:"pistaLlegada,omitempty"`
	HoraLlegada          string   `protobuf:"bytes,4,opt,name=horaLlegada,proto3" json:"horaLlegada,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectArrivals) Reset()         { *m = ObjectArrivals{} }
func (m *ObjectArrivals) String() string { return proto.CompactTextString(m) }
func (*ObjectArrivals) ProtoMessage()    {}
func (*ObjectArrivals) Descriptor() ([]byte, []int) {
	return fileDescriptor_795ccb07a121a6dd, []int{14}
}

func (m *ObjectArrivals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectArrivals.Unmarshal(m, b)
}
func (m *ObjectArrivals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectArrivals.Marshal(b, m, deterministic)
}
func (m *ObjectArrivals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectArrivals.Merge(m, src)
}
func (m *ObjectArrivals) XXX_Size() int {
	return xxx_messageInfo_ObjectArrivals.Size(m)
}
func (m *ObjectArrivals) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectArrivals.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectArrivals proto.InternalMessageInfo

func (m *ObjectArrivals) GetCodigoAvion() string {
	if m != nil {
		return m.CodigoAvion
	}
	return ""
}

func (m *ObjectArrivals) GetProveniente() string {
	if m != nil {
		return m.Proveniente
	}
	return ""
}

func (m *ObjectArrivals) GetPistaLlegada() string {
	if m != nil {
		return m.PistaLlegada
	}
	return ""
}

func (m *ObjectArrivals) GetHoraLlegada() string {
	if m != nil {
		return m.HoraLlegada
	}
	return ""
}

func init() {
	proto.RegisterType((*DataAvion)(nil), "proto.dataAvion")
	proto.RegisterType((*ResponseTorre)(nil), "proto.responseTorre")
	proto.RegisterType((*DataDespegue)(nil), "proto.dataDespegue")
	proto.RegisterType((*ResponseDespegue)(nil), "proto.responseDespegue")
	proto.RegisterType((*DataAterrizaje)(nil), "proto.dataAterrizaje")
	proto.RegisterType((*ResponseAterrizaje)(nil), "proto.responseAterrizaje")
	proto.RegisterType((*DataDestino)(nil), "proto.dataDestino")
	proto.RegisterType((*ResponseDestino)(nil), "proto.responseDestino")
	proto.RegisterType((*AvisoDespegue)(nil), "proto.AvisoDespegue")
	proto.RegisterType((*ResponseMensaje)(nil), "proto.responseMensaje")
	proto.RegisterType((*Mensajes)(nil), "proto.mensajes")
	proto.RegisterType((*ResponseDepartures)(nil), "proto.responseDepartures")
	proto.RegisterType((*ResponseArrivals)(nil), "proto.responseArrivals")
	proto.RegisterType((*ObjectDepartures)(nil), "proto.ObjectDepartures")
	proto.RegisterType((*ObjectArrivals)(nil), "proto.ObjectArrivals")
}

func init() { proto.RegisterFile("metadatos.proto", fileDescriptor_795ccb07a121a6dd) }

var fileDescriptor_795ccb07a121a6dd = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdb, 0x6e, 0x13, 0x3b,
	0x14, 0xcd, 0x34, 0x97, 0x26, 0x3b, 0xcd, 0xe5, 0xb8, 0xb7, 0x9c, 0xa8, 0x0f, 0x91, 0x55, 0x9d,
	0x53, 0x40, 0xaa, 0x44, 0x91, 0x40, 0x82, 0x17, 0x42, 0x8b, 0x44, 0x24, 0x2a, 0x50, 0xda, 0x1f,
	0x70, 0x33, 0x56, 0x70, 0x35, 0x1d, 0x0f, 0xb6, 0x27, 0x42, 0x7c, 0x04, 0xe2, 0x11, 0xf1, 0x04,
	0x3f, 0xc7, 0x77, 0xa0, 0xf1, 0xd8, 0x33, 0x76, 0xd2, 0x00, 0x7d, 0xe1, 0x29, 0xd9, 0xcb, 0x7b,
	0xf6, 0xac, 0xb5, 0xbc, 0xec, 0x81, 0xde, 0x0d, 0x55, 0x24, 0x24, 0x8a, 0xcb, 0xe3, 0x44, 0x70,
	0xc5, 0x51, 0x5d, 0xff, 0xe0, 0xef, 0x01, 0xb4, 0x42, 0xa2, 0xc8, 0x78, 0xc1, 0x78, 0x8c, 0x0e,
	0xa0, 0x45, 0xa8, 0xe0, 0x11, 0x8b, 0x29, 0x19, 0x04, 0xa3, 0xe0, 0xa8, 0x35, 0x2d, 0x01, 0xb4,
	0x07, 0x8d, 0x19, 0x0f, 0xd9, 0x9c, 0x0f, 0x36, 0xf4, 0x92, 0xa9, 0xd0, 0x00, 0x36, 0x13, 0x2a,
	0xf9, 0x39, 0xf9, 0x30, 0xa8, 0x8e, 0x82, 0xa3, 0xfa, 0xd4, 0x96, 0xd9, 0xbc, 0x53, 0x92, 0x5c,
	0x92, 0xf8, 0x7d, 0x4a, 0x07, 0x35, 0xbd, 0x56, 0x02, 0xe8, 0x3f, 0xe8, 0xb2, 0xe4, 0x92, 0x0b,
	0x41, 0x27, 0x31, 0x9b, 0x31, 0x12, 0x0d, 0xea, 0x7a, 0xee, 0x12, 0x8a, 0xc7, 0xd0, 0x11, 0x54,
	0x26, 0x3c, 0x96, 0x54, 0xe3, 0x19, 0x11, 0x2a, 0x15, 0x09, 0xb9, 0xe6, 0xd8, 0x9c, 0x9a, 0x2a,
	0x23, 0x72, 0x43, 0x63, 0x49, 0xae, 0xa9, 0x61, 0x68, 0x4b, 0xfc, 0x2d, 0x80, 0xad, 0x4c, 0xe6,
	0x19, 0x95, 0x09, 0x9d, 0xa7, 0x34, 0x6b, 0x0d, 0xa9, 0x54, 0x2c, 0xe6, 0x46, 0xa7, 0x2d, 0x7d,
	0x0f, 0x36, 0xd6, 0x7b, 0x50, 0xf5, 0x3c, 0xd8, 0x81, 0x7a, 0xc2, 0xa4, 0x22, 0x46, 0x65, 0x5e,
	0xa0, 0xfb, 0xd0, 0x97, 0x74, 0x9e, 0xc6, 0x21, 0x99, 0xc4, 0x52, 0x91, 0x78, 0xc6, 0x88, 0xd6,
	0xd8, 0x9c, 0xae, 0xe0, 0xf8, 0x73, 0x00, 0x7d, 0x2b, 0xb3, 0xa0, 0xb9, 0x4e, 0xe9, 0x01, 0xb4,
	0x58, 0x62, 0x05, 0x18, 0x92, 0x05, 0xe0, 0xfa, 0x50, 0xf5, 0x7c, 0x58, 0x43, 0x73, 0x0f, 0x1a,
	0x24, 0x52, 0xa9, 0xc8, 0xc9, 0xd5, 0xa7, 0xa6, 0xc2, 0x3f, 0x02, 0xe8, 0xea, 0x70, 0x28, 0x2a,
	0x04, 0xfb, 0x98, 0x0d, 0xf8, 0xbb, 0x09, 0x39, 0x84, 0x8e, 0xc9, 0xc2, 0x78, 0xa6, 0xd2, 0x22,
	0x20, 0x3e, 0x58, 0x8a, 0x6a, 0xfc, 0xce, 0xfb, 0xcd, 0x35, 0xde, 0x2b, 0x40, 0xd6, 0x7a, 0x47,
	0xeb, 0x9d, 0x63, 0x56, 0x32, 0xa9, 0xde, 0x6e, 0x6f, 0xcd, 0xb3, 0xf7, 0x7f, 0x68, 0x9b, 0x4c,
	0xda, 0x5d, 0xbb, 0x3d, 0x92, 0xf8, 0x1e, 0xf4, 0x9c, 0x64, 0xe8, 0xe6, 0x35, 0xdc, 0xf0, 0x05,
	0x74, 0xc6, 0x0b, 0x26, 0x79, 0x91, 0xa0, 0x82, 0x52, 0xb0, 0x44, 0xe9, 0xd6, 0x8d, 0xda, 0x81,
	0x7a, 0x94, 0xce, 0x89, 0x30, 0xb9, 0xc9, 0x0b, 0xfc, 0xa0, 0x7c, 0xff, 0xb9, 0x51, 0xea, 0x78,
	0x10, 0xf8, 0x47, 0xed, 0x10, 0x9a, 0xe6, 0xaf, 0xfc, 0x45, 0xd7, 0x79, 0xe9, 0xf8, 0x19, 0x4d,
	0x88, 0x50, 0xa9, 0xa0, 0x12, 0x3d, 0x01, 0x08, 0x8b, 0x6a, 0x10, 0x8c, 0xaa, 0x47, 0xed, 0x93,
	0xfd, 0xfc, 0xc2, 0x3a, 0x7e, 0x73, 0x75, 0x4d, 0x67, 0xaa, 0x6c, 0x9e, 0x3a, 0xad, 0xf8, 0x65,
	0x79, 0x76, 0xc6, 0x42, 0xb0, 0x05, 0x89, 0x24, 0x7a, 0x08, 0x4d, 0x62, 0xfe, 0x9b, 0x51, 0xbb,
	0xde, 0x28, 0xdb, 0x38, 0x2d, 0xda, 0xf0, 0x97, 0x00, 0xfa, 0xcb, 0xef, 0x41, 0x23, 0x68, 0xe7,
	0xee, 0xe8, 0x3b, 0xd2, 0x08, 0x71, 0x21, 0x77, 0xe7, 0x36, 0xfc, 0xcb, 0xe4, 0x10, 0x3a, 0xda,
	0x70, 0xbb, 0x1d, 0xc6, 0x57, 0x1f, 0x44, 0x18, 0xb6, 0xde, 0x71, 0x51, 0x36, 0xd5, 0x74, 0x93,
	0x87, 0xe1, 0xaf, 0x01, 0x74, 0x7d, 0xde, 0x7f, 0x40, 0x6c, 0x04, 0xed, 0x44, 0xf0, 0x05, 0x8d,
	0x19, 0x8d, 0x95, 0x4d, 0xab, 0x0b, 0x65, 0xaf, 0xd6, 0x5c, 0x5e, 0x47, 0x74, 0x4e, 0x42, 0x62,
	0xf8, 0x79, 0x58, 0x36, 0x25, 0xa3, 0x62, 0x5b, 0x72, 0x76, 0x2e, 0x74, 0xf2, 0xa9, 0x06, 0xd5,
	0xf1, 0xdb, 0x09, 0x7a, 0x06, 0xbd, 0xb3, 0xec, 0x1b, 0xf3, 0x8a, 0xcc, 0x18, 0x51, 0xfa, 0xae,
	0xee, 0x1b, 0xcf, 0x8b, 0x8f, 0xcc, 0x70, 0xc7, 0x20, 0xde, 0x9d, 0x8e, 0x2b, 0xe8, 0x39, 0xf4,
	0x4f, 0xf9, 0x4d, 0x22, 0xf8, 0x15, 0x11, 0x36, 0xe6, 0xc8, 0x79, 0xda, 0x60, 0xc3, 0xbd, 0xa5,
	0xe7, 0x0d, 0x8e, 0x2b, 0xe8, 0x14, 0xfe, 0xb9, 0xe0, 0x11, 0x9b, 0x31, 0xa5, 0x27, 0xe4, 0xe6,
	0x6e, 0xfb, 0x23, 0x34, 0x38, 0xdc, 0x5f, 0x9d, 0x91, 0xdb, 0x5c, 0x41, 0x13, 0xd8, 0x2e, 0x86,
	0x38, 0x97, 0xc1, 0xae, 0xab, 0xa3, 0x80, 0x87, 0xff, 0x2e, 0x0d, 0x2a, 0x97, 0xb4, 0xa2, 0x6e,
	0x76, 0x18, 0x1d, 0x32, 0x56, 0xbb, 0x77, 0x46, 0x57, 0x14, 0x99, 0x43, 0x86, 0x2b, 0xe8, 0x05,
	0xf4, 0xf3, 0x09, 0x0e, 0x93, 0xbb, 0xce, 0x78, 0x0a, 0xe0, 0xa4, 0xb9, 0x67, 0xfa, 0xec, 0x19,
	0x5d, 0x51, 0x50, 0xf6, 0xe2, 0x0a, 0x7a, 0x0c, 0xcd, 0x22, 0x6e, 0x2b, 0x4f, 0x2e, 0x9b, 0x68,
	0x3b, 0x71, 0xe5, 0xaa, 0xa1, 0x57, 0x1e, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x91, 0xf3,
	0x42, 0x77, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	DatosHaciatorre(ctx context.Context, in *DataAvion, opts ...grpc.CallOption) (*ResponseTorre, error)
	ComprobarDestino(ctx context.Context, in *DataDestino, opts ...grpc.CallOption) (*ResponseDestino, error)
	SolicitarDespegue(ctx context.Context, in *DataDespegue, opts ...grpc.CallOption) (*ResponseDespegue, error)
	SolicitarAterrizaje(ctx context.Context, in *DataAterrizaje, opts ...grpc.CallOption) (*ResponseAterrizaje, error)
	AvisarDespegue(ctx context.Context, in *AvisoDespegue, opts ...grpc.CallOption) (*ResponseMensaje, error)
	AvisarAterrizaje(ctx context.Context, in *AvisoDespegue, opts ...grpc.CallOption) (*ResponseMensaje, error)
	Departures(ctx context.Context, in *Mensajes, opts ...grpc.CallOption) (*ResponseDepartures, error)
	Arrivals(ctx context.Context, in *Mensajes, opts ...grpc.CallOption) (*ResponseArrivals, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) DatosHaciatorre(ctx context.Context, in *DataAvion, opts ...grpc.CallOption) (*ResponseTorre, error) {
	out := new(ResponseTorre)
	err := c.cc.Invoke(ctx, "/proto.API/DatosHaciatorre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ComprobarDestino(ctx context.Context, in *DataDestino, opts ...grpc.CallOption) (*ResponseDestino, error) {
	out := new(ResponseDestino)
	err := c.cc.Invoke(ctx, "/proto.API/ComprobarDestino", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SolicitarDespegue(ctx context.Context, in *DataDespegue, opts ...grpc.CallOption) (*ResponseDespegue, error) {
	out := new(ResponseDespegue)
	err := c.cc.Invoke(ctx, "/proto.API/SolicitarDespegue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SolicitarAterrizaje(ctx context.Context, in *DataAterrizaje, opts ...grpc.CallOption) (*ResponseAterrizaje, error) {
	out := new(ResponseAterrizaje)
	err := c.cc.Invoke(ctx, "/proto.API/SolicitarAterrizaje", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AvisarDespegue(ctx context.Context, in *AvisoDespegue, opts ...grpc.CallOption) (*ResponseMensaje, error) {
	out := new(ResponseMensaje)
	err := c.cc.Invoke(ctx, "/proto.API/AvisarDespegue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AvisarAterrizaje(ctx context.Context, in *AvisoDespegue, opts ...grpc.CallOption) (*ResponseMensaje, error) {
	out := new(ResponseMensaje)
	err := c.cc.Invoke(ctx, "/proto.API/AvisarAterrizaje", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Departures(ctx context.Context, in *Mensajes, opts ...grpc.CallOption) (*ResponseDepartures, error) {
	out := new(ResponseDepartures)
	err := c.cc.Invoke(ctx, "/proto.API/Departures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Arrivals(ctx context.Context, in *Mensajes, opts ...grpc.CallOption) (*ResponseArrivals, error) {
	out := new(ResponseArrivals)
	err := c.cc.Invoke(ctx, "/proto.API/Arrivals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	DatosHaciatorre(context.Context, *DataAvion) (*ResponseTorre, error)
	ComprobarDestino(context.Context, *DataDestino) (*ResponseDestino, error)
	SolicitarDespegue(context.Context, *DataDespegue) (*ResponseDespegue, error)
	SolicitarAterrizaje(context.Context, *DataAterrizaje) (*ResponseAterrizaje, error)
	AvisarDespegue(context.Context, *AvisoDespegue) (*ResponseMensaje, error)
	AvisarAterrizaje(context.Context, *AvisoDespegue) (*ResponseMensaje, error)
	Departures(context.Context, *Mensajes) (*ResponseDepartures, error)
	Arrivals(context.Context, *Mensajes) (*ResponseArrivals, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_DatosHaciatorre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataAvion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DatosHaciatorre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/DatosHaciatorre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DatosHaciatorre(ctx, req.(*DataAvion))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ComprobarDestino_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDestino)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ComprobarDestino(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ComprobarDestino",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ComprobarDestino(ctx, req.(*DataDestino))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SolicitarDespegue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDespegue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SolicitarDespegue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/SolicitarDespegue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SolicitarDespegue(ctx, req.(*DataDespegue))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SolicitarAterrizaje_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataAterrizaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SolicitarAterrizaje(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/SolicitarAterrizaje",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SolicitarAterrizaje(ctx, req.(*DataAterrizaje))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AvisarDespegue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvisoDespegue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AvisarDespegue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/AvisarDespegue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AvisarDespegue(ctx, req.(*AvisoDespegue))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AvisarAterrizaje_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvisoDespegue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AvisarAterrizaje(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/AvisarAterrizaje",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AvisarAterrizaje(ctx, req.(*AvisoDespegue))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Departures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensajes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Departures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/Departures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Departures(ctx, req.(*Mensajes))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Arrivals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensajes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Arrivals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/Arrivals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Arrivals(ctx, req.(*Mensajes))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DatosHaciatorre",
			Handler:    _API_DatosHaciatorre_Handler,
		},
		{
			MethodName: "ComprobarDestino",
			Handler:    _API_ComprobarDestino_Handler,
		},
		{
			MethodName: "SolicitarDespegue",
			Handler:    _API_SolicitarDespegue_Handler,
		},
		{
			MethodName: "SolicitarAterrizaje",
			Handler:    _API_SolicitarAterrizaje_Handler,
		},
		{
			MethodName: "AvisarDespegue",
			Handler:    _API_AvisarDespegue_Handler,
		},
		{
			MethodName: "AvisarAterrizaje",
			Handler:    _API_AvisarAterrizaje_Handler,
		},
		{
			MethodName: "Departures",
			Handler:    _API_Departures_Handler,
		},
		{
			MethodName: "Arrivals",
			Handler:    _API_Arrivals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadatos.proto",
}
